mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
    
    
   
]

news/urls.py
from django.urls import path
from .views import *
urlpatterns = [
  
    path('home', Home.as_view(), name='home'),
    path('news-submit-action', news_submit_action, name='news-submit-action'),
    path('aboutme', about_me.as_view(), name='aboutme'),

    path('employee_insert', employee_form, name='employee_insert'),
    
    path('employee_list/',employee_list,name='employee_list'), # Rename the view of pervious one
    path('employee_update/<int:id>/',employee_form,name='employee_update'),
    path('employee_delete/<int:id>/',employee_delete,name='employee_delete'),

    path('employee_login', employee_login_view, name='employee-login'),

    path('employee-login-sbmit', employee_login_view, name='employee-login-sbmit'),
    path('employee-signup', employee_signup, name='employee-signup'),


    path('product-create-view', product_create_view.as_view(), name='product-create-view'),
    path('product-create-insert', product_create_insert, name='product-create-insert'),


    
    
    
    path('sales-create-view', sales_create_view.as_view(), name='sales-create-view'),
    path('sales-create-insert', sales_create_insert, name='sales-create-insert'),
    path('get-product-info/<slug:product_code>', get_product_info, name='get-product-info'),


    
    path('client_form',client_form,name='client_form'),
    path('client_update/<int:id>/',client_form,name='client_update'),
    path('client_list',client_list,name='client_list'),
    path('client_delete/<int:id>/',client_delete,name='client_delete'),

   


   path('account_oppening', account_oppening.as_view(), name='account_oppening'),
   path('account-create-insert', account_create_insert, name='account-create-insert'),

     

    





  

]

news/models.py
from django.db import models
from django import forms


class Reporter(models.Model):
    full_name = models.CharField(max_length=70)
    def __str__(self):
        return self.full_name
class Article(models.Model):
    pub_date = models.DateField()
    headline = models.CharField(max_length=200)
    content = models.TextField()
    reporter = models.ForeignKey(Reporter, on_delete=models.CASCADE)

    def __str__(self):
        return self.headline

class My_Info(models.Model):
    first_name =  models.CharField(max_length=200)
    last_name =  models.CharField(max_length=200)


class Position(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title

class Employee(models.Model):
    fullname = models.CharField(max_length=100)
    emp_code = models.CharField(max_length=4)
    mobile= models.CharField(max_length=15)
    position= models.ForeignKey(Position,on_delete=models.CASCADE)
    



class Products(models.Model):
    product_code = models.CharField(max_length=100, primary_key=True)
    product_name = models.CharField(max_length=100)
    sales_price = models.DecimalField(max_digits=22, decimal_places=2,default=0.00, blank=True)
    total_sales = models.IntegerField(blank=True,null=True)
    app_user_id = models.CharField(max_length=200,blank=False, null=True)
    app_data_time = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.product_name

class Products_Sales(models.Model):
    product_code = models.ForeignKey(Products,on_delete=models.PROTECT)
    unit_price = models.DecimalField(max_digits=22, decimal_places=2,default=0.00, blank=True)
    total_quantity = models.IntegerField()
    total_price = models.DecimalField(max_digits=22, decimal_places=2,default=0.00, blank=True)
    app_user_id = models.CharField(max_length=200,blank=True, null=True)
    app_data_time = models.DateTimeField(auto_now_add=True)






class client_account(models.Model):
    account_number=models.IntegerField(primary_key=True)
    client_name=models.CharField(max_length=10)
    client_address=models.CharField(max_length=10)
    client_nid=models.IntegerField()
    date_of_birth = models.DateField()
    totoal_deposit=models.IntegerField(null=True, blank=True)
    total_withdwral=models.IntegerField(null=True, blank=True)
    account_balance=models.IntegerField(null=True, blank=True)
    app_user_id=models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.client_name
    

CHOICES=(
    ('D','Withdrwal'),
    ('c','Deposit'),
)


class Account_Transaction(models.Model):
    account_number=models.ForeignKey(client_account,on_delete=models.PROTECT)
    transaction_type =models.CharField(max_length=300, choices = CHOICES)
    transaction_amount=models.IntegerField()
    transaction_comments=models.CharField(max_length=100)
    app_user_id=models.IntegerField(null=True, blank=True)
    app_data_time=models.DateField(auto_now_add=True)
    date_of_birth = models.DateField(null=True, blank=True)



class Regions(models.Model):
    region_id = models.CharField(max_length=20, primary_key=True)
    region_name = models.CharField(max_length=200, blank=True, null=True)

class Jobs(models.Model):
    job_id = models.CharField(max_length=20, primary_key=True)
    job_title = models.CharField(max_length=200, blank=True, null=True)
    min_salary = models.IntegerField(blank=True, null=True)
    max_salary = models.IntegerField(blank=True, null=True)


class Countries(models.Model):
    country_id = models.CharField(max_length=20, primary_key=True)
    country_name = models.CharField(max_length=200, blank=True, null=True)
    region_id = models.IntegerField(blank=True, null=True)


class Locations(models.Model):
    location_id = models.IntegerField( primary_key=True)
    street_address = models.CharField(max_length=200, blank=True, null=True)
    postal_code = models.CharField(max_length=20, blank=True, null=True)
    city = models.CharField(max_length=200, blank=True, null=True)
    state_province = models.CharField(max_length=200, blank=True, null=True)
    country_id = models.CharField(max_length=20, blank=True, null=True)

class Departments(models.Model):
    department_id = models.IntegerField( primary_key=True)
    department_name = models.CharField(max_length=200, blank=True, null=True)
    manager_id = models.IntegerField(blank=True, null=True)
    location_id = models.IntegerField(blank=True, null=True)


class Employees(models.Model):
    employee_id = models.IntegerField( primary_key=True)
    first_name = models.CharField(max_length=200, blank=True, null=True)
    last_name = models.CharField(max_length=200, blank=True, null=True)
    email = models.CharField(max_length=200, blank=True, null=True)
    phone_number = models.CharField(max_length=200, blank=True, null=True)
    hire_date = models.DateField(null=True)
    job_id = models.CharField(max_length=200, blank=True, null=True)
    salary = models.DecimalField(max_digits=22, decimal_places=2,default=0.00, blank=True,null=True)
    commission_pct = models.DecimalField(max_digits=22, decimal_places=2,default=0.00, blank=True,null=True)
    manager_id = models.IntegerField(blank=True, null=True)
    department_id = models.IntegerField(blank=True, null=True)

class Job_History(models.Model):
    employee_id = models.IntegerField(blank=True, null=True)
    start_date =  models.DateField(null=True)
    end_date =  models.DateField(null=True)
    job_id =  models.CharField(max_length=20, blank=True, null=True)
    department_id = models.IntegerField(blank=True, null=True)

class department(models.Model):
    
    dep_name=models.CharField(max_length=100,blank=False)
    dep_id=models.CharField( primary_key=True,auto_created=True,max_length=122)
    dep_location=models.CharField(max_length=200)
    app_user_id=models.CharField(max_length=100,blank=True)
    # app_data_time=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.dep_name

news/views.py
from django.shortcuts import render,redirect
from django.views.generic import TemplateView
from.models import *


from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from .forms import EmployeeForm
from .models import Employee
from django.shortcuts import render, redirect

from .forms import clieantAccountFrom
from .models import client_account

   
from django.db import connection, transaction
from .forms import *
import json
from django.http import JsonResponse


# Create your views here.
class Home(TemplateView):
    template_name='news/bootstrap.html'

def news_submit_action(request):
    print("Hello")
    fname = request.GET["fname"]
    lname = request.GET["lname"]
    mydata = My_Info(first_name=fname, last_name=lname)
    mydata.save()
    print(fname)
    print(lname)
    return render(request, 'news/index.html')



class about_me(TemplateView):
    template_name='news/aboutme.html'
    def get(self, request):
        data = dict()
        request.session["user_full_name"] = "Full Name"
        data["user_full_name"]=request.session["user_full_name"]
        return render(request, self.template_name, data)




def employee_form(request, id=0):
    
    if request.method == "GET":
        if id == 0:
            form = EmployeeForm()
        else:
            employee = Employee.objects.get(pk=id)
            form = EmployeeForm(instance=employee)
        return render(request, "news/employee_form.html", {'form': form})
    else:
        if id == 0:
            form = EmployeeForm(request.POST)
        else:
            employee = Employee.objects.get(pk=id)
            form = EmployeeForm(request.POST,instance= employee)
        if form.is_valid():
            form.save()
        return redirect('employee_list')


def employee_list(request):
    context = {'employee_list': Employee.objects.all()}
    return render(request, "news/employee_list.html", context)

def employee_delete(request,id):
    employee = Employee.objects.get(pk=id)
    employee.delete()
    return redirect('employee_list')



def employee_login_view(request):
    if request.method=='GET':
        return render(request,'news/employee_login.html')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                request.session["app_user_id"]=username
                return redirect('employee_list')
        else:
            return render(request,'news/employee_login.html',{'message':"invalid username and password"})



def employee_signup(request):
    if request.method == "GET":
        return render(request, "news/employee-signup.html")
    else:
        username = request.POST.get('username', False)
        password = request.POST.get('password', False)
        confirm_password = request.POST.get('confirm_password', False)

        if len(username)==0 or len(password)==0:
            return render(request, "news/employee-signup.html", {"message": "Please check your Input"})

        if password != confirm_password:
            return render(request, "news/employee-signup.html", {"message": "Password and Confirm Password does't match"})
        else:
            user = User.objects.create_user(username, '', password)
            user.save()
        return render(request, 'news/employee_login.html')

 


class product_create_view(TemplateView):
    template_name = 'news/product-create.html'

    def get(self, request):
        if not request.user.is_authenticated:
            return render(request, 'news/employee_login.html')
        data = dict()
        form = ProductsModelForm()
        data['form']=form
        return render(request, self.template_name, data)

@transaction.atomic
def product_create_insert(request):
    if not request.user.is_authenticated:
        return render(request, 'news/employee_login.html')
    data=dict()
    data['form_is_valid'] = False

    if request.method=='POST':
        form = ProductsModelForm(request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    app_user_id = request.session["app_user_id"]

                    sales_price = form.cleaned_data['sales_price']
                    product_code = form.cleaned_data['product_code']

                    if Products.objects.filter(product_code=product_code).exists():
                        data['error_message']='Product Code Already Exist!'
                        return JsonResponse(data)

                    if sales_price<0:
                        data['error_message']='Sales price should not be negative values!'
                        return JsonResponse(data)

                    post = form.save(commit=False)
                    post.app_user_id = app_user_id
                    post.save()
                    data['form_is_valid'] = True
                    data['succ_message'] = "Save Successfully"
            except Exception as e:
                print(str(e))
                data['form_is_valid'] = False
                data['error_message']=str(e)
                return JsonResponse(data)
        else:
            data['error_message']=form.errors.as_json()
    return JsonResponse(data)


class sales_create_view(TemplateView):
    template_name = 'news/product-sales.html'

    def get(self, request):
        if not request.user.is_authenticated:
            return render(request, 'news/employee_login.html')
        data = dict()
        form = ProductsSalesModelForm()
        data['form'] = form
        return render(request, self.template_name, data)


@transaction.atomic
def sales_create_insert(request):
    if not request.user.is_authenticated:
        return render(request, 'news/employee_login.html')
    data=dict()
    data['form_is_valid'] = False

    if request.method=='POST':
        form = ProductsSalesModelForm(request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    app_user_id = request.session["app_user_id"]
                    product_code = form.cleaned_data['product_code']

                    post = form.save(commit=False)
                    post.app_user_id = app_user_id
                    post.save()
                    data['form_is_valid'] = True
                    data['succ_message'] = "Save Successfully"
            except Exception as e:
                print(str(e))
                data['form_is_valid'] = False
                data['error_message']=str(e)
                return JsonResponse(data)
        else:
            data['error_message']=form.errors.as_json()
    return JsonResponse(data)


def get_product_info(request, product_code):

    data = dict()
    product_name=''
    sales_price=0
    try:
        product_info = Products.objects.get(product_code=product_code)
        product_name = product_info.product_name
        sales_price = product_info.sales_price
    except Exception as e:
        product_name = ''
        sales_price=0

    data['product_name']=product_name
    data['sales_price']=sales_price
    data['form_is_valid'] = True
    return JsonResponse(data)





def client_form(request, id=0):
    if request.method == "GET":
        if id == 0:
            form = clieantAccountFrom()
        else:
            client = client_account.objects.get(pk=id)
            form = clieantAccountFrom(instance=client)
        return render(request, "news/client_account.html", {'form': form})
    else:
        if id == 0:
            form = clieantAccountFrom(request.POST)
        else:
            client = client_account.objects.get(pk=id)
            form = clieantAccountFrom(request.POST,instance= client)
        if form.is_valid():
            form.save()
        return redirect('client_list')

def client_list(request):
    query=client_account.objects.all()
    dict={'query':query}
    return render(request,'news/client_list.html',context=dict)

def client_delete(request,id):
    client = client_account.objects.get(pk=id)
    client.delete()
    return redirect('client_list')





class account_oppening(TemplateView):

    template_name = 'news/account_create.html'

    def get(self, request):
        if not request.user.is_authenticated:
            return render(request, 'news/client_login.html')
        data = dict()
        form = accounttransactionForm()
        data['form']=form
        return render(request, self.template_name, data)



@transaction.atomic
def account_create_insert(request):
    if not request.user.is_authenticated:
        return render(request, 'news/client_login.html')
    data=dict()
    data['form_is_valid'] = False

    if request.method=='POST':
        form = accounttransactionForm(request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    app_user_id = request.session["app_user_id"]
                    account_number = form.cleaned_data['account_number']

                    if Account_Transaction.objects.filter(account_number=account_number).exists():
                        data['error_message']='account_number Already Exist!'
                        return JsonResponse(data)

                        

                    # if sales_price<0:
                    #     data['error_message']='Sales price should not be negative values!'
                    #     return JsonResponse(data)

                    post = form.save(commit=False)
                    post.app_user_id = app_user_id
                    post.save()
                    data['form_is_valid'] = True
                    data['succ_message'] = "Save Successfully"
            except Exception as e:
                print(str(e))

templates/news/account_create.html
{% extends "news/base_js.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-lg-12">
        <div class="card card-fluid">
            <div class="card-body">
                <div>
                    <form method="post" id="tran_table_data" data-url="{% url 'account-create-insert' %}"
                        class="update-form">
                        <div class="form-group">
                            <div class="card">
                                <div class="card-body">
                                    <div class="form-row">
                                        <div class="form-item col-md-10 mb-0">
                                            <h3 class="card-title">account Create</h3>
                                        </div>
                                    </div>
                                    <div>
                                        {% csrf_token %}
                                        <div class="form-row">
                                            <div class="form-item col-md-4 mb-0">
                                                {{ form.account_number|as_crispy_field }}
                                            </div>
                                            <div class="form-item col-md-4 mb-0">
                                                {{ form.transaction_type|as_crispy_field }}
                                            </div>
                                            <div class="form-item col-md-4 mb-0">
                                                {{ form.transaction_amount|as_crispy_field }}
                                            </div>
                                            <div class="form-item col-md-4 mb-0">
                                                {{ form.transaction_comments|as_crispy_field }}
                                            </div>
                                            <div class="form-item col-md-4 mb-0">
                                                {{ form.date_of_birth|as_crispy_field }}
                                            </div>
                                            
                                        </div>
                                        <button type="button" id="btnAddItem" class="btn btn-primary">account transaction</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    {% endblock content %}

    {% block js %}

    <script>

        $(function () {

            $(function () {
                $('#btnAddItem').click(function () {
                    post_tran_table_data();
                });
            });

            function post_tran_table_data() {
                var data_string = $("#tran_table_data").serialize();
                var data_url = $("#tran_table_data").attr('data-url');
                $.ajax({
                    url: data_url,
                    data: data_string,
                    type: 'POST',
                    dataType: 'json',
                    success: function (data) {
                        if (data.form_is_valid) {
                            document.getElementById("tran_table_data").reset();
                            alert(data.succ_message);
                        } else {
                            alert(data.error_message);
                        }
                    }
                })
                return false;
            }

            function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie != '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = jQuery.trim(cookies[i]);
                        if (cookie.substring(0, name.length + 1) == (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }

            var csrftoken = getCookie('csrftoken');

            function csrfSafeMethod(method) {
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }
            function sameOrigin(url) {
                var host = document.location.host; // host + port
                var protocol = document.location.protocol;
                var sr_origin = '//' + host;
                var origin = protocol + sr_origin;
                return (url == origin || url.slice(0, origin.length + 1) == origin + '/') ||
                    (url == sr_origin || url.slice(0, sr_origin.length + 1) == sr_origin + '/') ||
                    !(/^(\/\/|http:|https:).*/.test(url));
            }

            $.ajaxSetup({
                beforeSend: function (xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && sameOrigin(settings.url)) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });

        });

    </script>


    {% endblock js %}

templates/news/bootstrap_static.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Employee Register</title>
    <link rel="stylesheet" href="{% static 'assets/stylesheets/bootstrap.min.css' %}">
</head>

<body>

    <div class="container">
        <div class="col-md-10 offset-md-1 mt-5">
            <div class="jumbotron">
                <h1 class="display-4">Employee Register</h1>
                <p class="lead font-italic">Python Django project for implementing CRUD operations</p>
					<button type="button" class="btn btn-success">Success</button>
            </div>
        </div>
    </div>

    <script src="{% static 'assets/javascript/bootstrap.min.js' %}"></script>

</body>

</html>

templates/news/index.html
<!DOCTYPE html>
<html>
        <head>
            <title>A simple webpage </title>
        </head>
        <body>
            <h1>Hello, world. You're at the news index.</h1>
           <from action="" method="post">
           First name: <input type="text" name="fname"><br>
           Last name: <input type="text" name="lname"><br>
           <input type="submit" value="Submit">

           </form>
  
        </body>
</html>

templates/news/product-sales.html
{% extends "news/base_js.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <!-- grid column -->
    <div class="col-lg-12">
        <!-- .card -->
        <div class="card card-fluid">
            <!-- .card-body -->
            <div class="card-body">
                <div>
                    <!--form method="post" novalidate-->
                    <form method="post" id="tran_table_data" data-url="{% url 'sales-create-insert' %}"
                        class="update-form">
                        <div class="form-group">
                            <!-- .card -->
                            <div class="card">
                                <!-- .card-body -->
                                <div class="card-body">
                                    <div class="form-row">
                                        <div class="form-item col-md-10 mb-0">
                                            <h3 class="card-title">Sales Product</h3>
                                            <!-- form .needs-validation -->
                                        </div>
                                    </div>
                                    <div>
                                        <!--form method="post" novalidate-->
                                        {% csrf_token %}
                                        <div class="form-row">
                                            <div class="form-item col-md-4 mb-0">
                                                {{ form.product_code|as_crispy_field }}
                                            </div>
                                            <div class="form-item col-md-4 mb-0">
                                                {{ form.product_name|as_crispy_field }}
                                            </div>
                                            <div class="form-item col-md-4 mb-0">
                                                {{ form.unit_price|as_crispy_field }}
                                            </div>
                                            <div class="form-item col-md-4 mb-0">
                                                {{ form.total_quantity|as_crispy_field }}
                                            </div>
                                            <div class="form-item col-md-4 mb-0">
                                                {{ form.total_price|as_crispy_field }}
                                            </div>
                                        </div>
                                        <button type="button" id="btnAddItem" class="btn btn-primary">Create
                                            Sales</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div><!-- /.card-body -->
            </div><!-- /.card -->
        </div>
        <!-- /grid column -->
    </div>

    {% endblock content %}

    {% block js %}

    <script>
        
        

        $(function () {

            $("#id_product_code").on("change paste keyup", function () {
                get_product_info();
            });

            function get_product_info() {
                var product_code = document.getElementById('id_product_code').value;
                $.ajax({
                    url: "get-product-info/" + product_code,
                    type: 'GET',
                    success: function (data) {
                        if (data.form_is_valid) {
                            // console.log(data.product_name)
                            $('#id_product_name').val(data.product_name);
                            $('#id_unit_price').val(data.sales_price);
                        } else {
                            $('#id_product_name').val('');
                            $('#id_unit_price').val('');
                        }
                    }
                })
                return false;
            }

            $("#id_total_quantity").on("change paste keyup", function () {
                var total_quantity = document.getElementById('id_total_quantity').value;
                var unit_price = document.getElementById('id_unit_price').value;
                var total_price = Number(unit_price) * Number(total_quantity);
                // console.log(total_price);
                $('#id_total_price').val(total_price);
            });

            $(function () {
                $('#btnAddItem').click(function () {
                    post_tran_table_data();

                });
            });

            function post_tran_table_data() {
                var data_string = $("#tran_table_data").serialize();
                var data_url = $("#tran_table_data").attr('data-url');
                $.ajax({
                    url: data_url,
                    data: data_string,
                    type: 'POST',
                    dataType: 'json',
                    success: function (data) {
                        if (data.form_is_valid) {
                            document.getElementById("tran_table_data").reset();
                            alert(data.succ_message);
                        } else {
                            alert(data.error_message);
                        }
                    }
                })
                return false;
            }

            function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie != '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = jQuery.trim(cookies[i]);
                        if (cookie.substring(0, name.length + 1) == (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }

            var csrftoken = getCookie('csrftoken');


            function csrfSafeMethod(method) {
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }
            function sameOrigin(url) {

                var host = document.location.host; // host + port
                var protocol = document.location.protocol;
                var sr_origin = '//' + host;
                var origin = protocol + sr_origin;
                return (url == origin || url.slice(0, origin.length + 1) == origin + '/') ||
                    (url == sr_origin || url.slice(0, sr_origin.length + 1) == sr_origin + '/') ||
                    !(/^(\/\/|http:|https:).*/.test(url));
            }

            $.ajaxSetup({
                beforeSend: function (xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && sameOrigin(settings.url)) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });

        });

    </script>


    {% endblock js %}